pipeline:
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Toggle-Flag-On-Off
        identifier: ToggleFlagOnOff
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  name: Turn-Flag-On
                  identifier: TurnFlagOn
                  template:
                    templateRef: account.Add_Targeting_Rule_for_segment_Boolean
                    versionLabel: Version1
                    gitBranch: main
                    templateInputs:
                      type: Http
                      spec:
                        inputVariables:
                          - name: workspace
                            type: String
                            value: <+pipeline.variables.SplitWorkspace>
                          - name: flagName
                            type: String
                            value: <+pipeline.variables.FlagName>
                          - name: environment
                            type: String
                            value: <+pipeline.variables.SplitEnvironment>
                          - name: on_variant
                            type: String
                            value: <+pipeline.variables.on_treatment>
                          - name: segmentName
                            type: String
                            value: <+pipeline.variables.UserSegments>
              - step:
                  type: HarnessApproval
                  name: HarnessApproval_1
                  identifier: HarnessApproval_1
                  spec:
                    approvalMessage: Approve to turn off
                    includePipelineExecutionHistory: true
                    isAutoRejectEnabled: false
                    approvers:
                      userGroups:
                        - account._account_all_users
                      minimumCount: 1
                      disallowPipelineExecutor: false
                    approverInputs: []
                  timeout: 1d
              - step:
                  name: Turn-Flag-Off
                  identifier: TurnFlagOff
                  template:
                    templateRef: account.Add_Targeting_Rule_for_segment_Boolean
                    versionLabel: Version1
                    gitBranch: main
                    templateInputs:
                      type: Http
                      spec:
                        inputVariables:
                          - name: workspace
                            type: String
                            value: <+pipeline.variables.SplitWorkspace>
                          - name: flagName
                            type: String
                            value: <+pipeline.variables.FlagName>
                          - name: environment
                            type: String
                            value: <+pipeline.variables.SplitEnvironment>
                          - name: on_variant
                            type: String
                            value: <+pipeline.variables.off_treatment>
                          - name: segmentName
                            type: String
                            value: <+pipeline.variables.UserSegments>
        tags: {}
  variables:
    - name: FlagName
      type: String
      description: ""
      required: true
      value: <+input>.allowedValues(boxes_richard,boxes_josh)
    - name: SplitWorkspace
      type: String
      description: ""
      required: true
      value: 4baf0690-6d25-11e9-8497-12a5cc2af8fe
    - name: SplitEnvironment
      type: String
      description: ""
      required: true
      value: 4bc2b5a0-6d25-11e9-8497-12a5cc2af8fe
    - name: on_treatment
      type: String
      description: ""
      required: true
      value: standard
    - name: off_treatment
      type: String
      description: ""
      required: true
      value: current
    - name: splitApiKey
      type: Secret
      description: ""
      required: true
      value: splitApiKey
    - name: UserSegments
      type: String
      description: ""
      required: true
      value: <+input>.allowedValues(trial_users_boxes,qa_boxes)
  identifier: Toggle_Flag_On_or_Off_User_Segment
  name: Toggle Flag On or Off - User Segment
